### ISSUE TITLE
move compiled js to a dist folder?

### ISSUE THREAD

**Issue by BIueLightning** [coloquium/greenscreenstream#10]
Right now the compiled js & js.maps just get thrown next to the ts files.
I think it would be much cleaner to move it into an dist directory instead.

Note that the  <ins>unbundled</ins> example .ts files would also be automaticly placed there.
So the webpack entry paths will need to be updated aswell. No big deal overall.

**Comment by MagnusThor** [comment]
True, i'll assign this to you.  I prefer you make a new branch and then we can create a pull request and merge?

**Comment by BIueLightning** [comment]
Done: 4cf77365b7c15c241b450e96be82c3fee6d2a874
Ended up just doing it in the refactor branch 😅

**Comment by MagnusThor** [comment]
Great, you merged with master?

**Comment by BIueLightning** [comment]
I'll check for potential bugs one more time, then I'll create a pull request.

Did you see the new quality options for bodypix I implemented?

In short:
Added config options as parameter in initialize() method.
      This config object consists of several optional parameters:
        - masksettings
        - BodyPixMode: An enum that loads a predefined bodypix model
        - BodyPixConfig: A custom config to load for bodypix. Overrides enum if both are provided.

Preconfigured BodyPixModes:
        - Fast: Very unprecise, but fast & small model.
        - Standard: The standard model recommended for most low power devices
        - Precise: More accuracy & less flimmering around the head but bigger and more performance hungry
        - Maximum: Maximal quality using the BodyPix ResNet Model. Very resource hungry and not recommended.
       
Presets:
https://github.com/coloquium/greenscreenstream/blob/refactor/src/models/bodypix-config.ts

Config interface:
https://github.com/coloquium/greenscreenstream/blob/refactor/src/models/green-screen-config.interface.ts

**Comment by BIueLightning** [comment]
Handled in #15
