### ISSUE TITLE
Library Logo

### ISSUE THREAD

**Issue by BIueLightning** [coloquium/greenscreenstream#11]
So we need to make a documentation, I thought why not make a logo for the package aswell? :D
I had to design some stuff recently so I created 3 drafts for a logo aswell:

<a href="https://ibb.co/x7cSz0T"><img src="https://i.ibb.co/x7cSz0T/gss-v1.png" alt="gss-v1" border="0"></a> <a href="https://ibb.co/gzXkKB6"><img src="https://i.ibb.co/gzXkKB6/gss-v2.png" alt="gss-v2" border="0"></a> <a href="https://ibb.co/LR8SDdw"><img src="https://i.ibb.co/LR8SDdw/gss-v3.png" alt="gss-v3" border="0"></a>

What do you think?

**Comment by MagnusThor** [comment]
Looks great, i vite for the first one..  Maybe usie it as a "lodader" image , draw it on the canvas during initialization?

**Comment by BIueLightning** [comment]
ok, number one it is then :)
I uploaded different sizes: [Google Drive Link](https://drive.google.com/drive/folders/1v7kR-Bo8UpEna8H2N0lVEaj5DON8xlHo?usp=sharing)

One version is titled "gss logo github".
You can set it as repository  logo in the repository settings.
