### ISSUE TITLE
feature: Swap background during rendering

### ISSUE THREAD

**Issue by MagnusThor** [coloquium/greenscreenstream#13]
Implement a feature that gives the possibility to change the background image/video source during rendering.

**Comment by MagnusThor** [comment]
@BIueLightning I just commited this feature ( branch ) and merged.   I suggest you create a pull request of the refacor branch of yours, align it to master.


Feature can be tested in the /mWebGL  example.

Any thoughts?

Magnus

**Comment by BIueLightning** [comment]
Very nice, I solved background changes with just restarting everything, 
this is much better!

**Comment by MagnusThor** [comment]
yes, shader compile and all init stuff willbe skipped. so you aprove .p

**Comment by MagnusThor** [comment]
Implemented and works well.
