### ISSUE TITLE
Feature: Show logo while loading

### ISSUE THREAD

**Issue by BIueLightning** [coloquium/greenscreenstream#14]
Adding the gss logo while the stream "loads" would be a nice touch.
Option to turn it off should be included however.

**Comment by MagnusThor** [comment]
Yes,  a replace of the file would be great, i look into that when possible,  you mat be faster than me ..

**Comment by MagnusThor** [comment]
@BIueLightning  , After som fiddling i came to the conclution that is a bit tricky as the drawingContext is locked to webgl, i trided to create a temporary one and shuffle the pixelData , but result was not good.  So i decided that we let the users of the package deal with that them self using the initializie promise, that way they any HTML Element of thier own.
