### ISSUE TITLE
Bump version to 3.0.0

### ISSUE THREAD

**Issue by BIueLightning** [coloquium/greenscreenstream#18]
We had some major breaking api changes and new features:
- Dynamic background change
- Body Pix Quality (also dynamically changeable) 
- (Optimizations)

I think it's only fair if we bump the version up to 3.0.0

**Comment by MagnusThor** [comment]
Okey, do that, also chnage the contrib settings, and add your profile there.  ill wait and till we fixed the documentation is finalized then we publish 3.x  on npm
