### ISSUE TITLE
[Feature Request]: stop rendering

### ISSUE THREAD

**Issue by BIueLightning** [coloquium/greenscreenstream#5]
Firstly, thanks for this awesome library, it works really well.

It would be really nice if it were possible to stop rendering.
If the object instance is deleted, greenscreenstream and demolishedrenderer 
are both still running their respective requestAnimationFrame() loops.

A public stop() method would be really helpful in this regard, the loops are rather performance hungry.

I'm using this module in an angular app and had to include both it and demolishedrenderer directly due to a problem with webpack, so I added the functionality myself:

demolishedRenderer: [link](https://github.com/BIueLightning/gameletconnect/blob/angularRollback/connectclient/src/app/classes/demolishedrenderer.ts)
greenscreenstream: [link](https://github.com/BIueLightning/gameletconnect/blob/angularRollback/connectclient/src/app/classes/greenscreenstream.ts)

**Comment by MagnusThor** [comment]
Thanks @BIueLightning  for the feedback and that you enjoy the library.    I will fix this , probably today or tomorrow.    

Can you elaborate on the angular issue of yours,   perhaps i can ensure such a work around?    Whould it be better if i removed the dependency for demolishedrenderer ,   it could actually be a better solution, even thou both libs are mine.

regards 

Magnus

**Comment by BIueLightning** [comment]
Thank you for your quick response :)

It's hard to say for me what's the issue, as I never used webpack on it's own and don't know much about it.
I'm using Angular 11 and thus webpack 4.6 .
I tried to google the issue and it seems it could have something to do with the webpack config.

I don't know if it's the angular default webpack config or the config in your repositories, a combination of both or something completely unrelated.

When I do a build and try to import greenscreenstream from node_modules i get the following error upon calling the constructor:
```js
TypeError: greenscreenstream__WEBPACK_IMPORTED_MODULE_7__.GreenScreenStream is not a constructor
    at rtc-settings.service.ts:278
    at new ZoneAwarePromise (zone-evergreen.js:960)
    at RtcSettingsService.getVirtualBackgroundStream (rtc-settings.service.ts:275)
    at MediasoupService.<anonymous> (mediasoup.service.ts:323)
    at Generator.next (<anonymous>)
    at fulfilled (tslib.es6.js:73)
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at zone-evergreen.js:857
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
```
If  I use ,getInstance(...) intead, the error changes to
```js 
TypeError: Cannot read property 'getInstance' of undefined
(same stack trace)
```
The same happens for demolishedRenderer if I include greenscreenstream manually and load DR from node_modules.
I don't think the dependency on DR is the problem here.

Regards

**Comment by MagnusThor** [comment]
Okey,  im at the moment refactoring GreenScreenStream,   start , stop and initialize stuff is currently beeing implemented,  as well as the calls to requestAnimationFrame is limided and separated to one single one.   good thing is that i can keep DR , webgl as is, and just modify the lib itself.

Maybe the problem with webpack is related to the getInstance method ? (Hmm) , that is a  kind of a singelton way of getting the instance, i look into that also.

**Comment by BIueLightning** [comment]
That sounds really cool!

If .getInstance is the cause, why does the normal constructor fail aswell? That doesn't really make sense to me^^

**Comment by MagnusThor** [comment]
True,  i will give it a try in Angular before a release,   also need to do some additional testing, but start, stop, pause as well as a separate RAF for the GreenScreenStream,  easier and more efficient.  

Timeing is much more accurate ,  DR renderer timeing was bit out of sync earlier.

So, i'll give you a message when published to NPM.

**Comment by MagnusThor** [comment]
@BIueLightning running out of time  but the end of the week we will have a new version put. ok?

**Comment by BIueLightning** [comment]
Hey, that sounds great, many thanks for your awesome work.
But please do not stress yourself. 

My own application is far from ready anyways :)

**Comment by MagnusThor** [comment]
@BIueLightning now its just the testing,  i did some small changes to the API , see the following gist 

https://gist.github.com/MagnusThor/715496c2a1c8baf9aaab5a871f5d2a30


.stop() and .start()   as wells as 1 single RAF ,   i'm not sure if a dispose() method is needed,  the ng or rect lifesycle can be an issue, so you may neded that?

q:   Maybe i can add you as contrib later and you can assist in dox etc?

Magnus

**Comment by MagnusThor** [comment]
@BIueLightning commited an update yesterday,  give me a ping after you checked.

**Comment by BIueLightning** [comment]
Hi, sorry for the late response, I was on vacation.
I copied your update and it works well. CPU usage drops significantly after calling .stop().
Thank you very much!
The webcam stays active after stopping though, maybe consider adding this line to the stop() method:
`this.mediaStream.getVideoTracks()[0].stop();`

Personally I don't need a .dispose() method as I keep the videoconferencing components/services alive the whole time without destroying and readding them.

Maybe it's worth considering for the future if more people decide to use this package.

You can sure add me as contrib. If I have time I will gladly help with the docs and maybe refactoring if that is ok :)

**Comment by MagnusThor** [comment]
@BIueLightning no worries.    Great that it is consuming less CPU, i also added an optinal argument to .stop(stopMediaStream) , if provided the media tracks stops. 

Regarging .dispose() i also concider this as a non needed thing. 

I have some shader updates that i want to implement as well, but as for now i think we take it from the last push.

Did some refactoring to the API, such as got rid of the onReady event, using Promises instad,  constructor changes came as a package of that :-)

I'll add you to the repo as contrib, feel free to just hack.

Let me know what you think of last changes, and if there is something needed from me.

Magnus

**Comment by MagnusThor** [comment]
Pushed some additinal stuff, fixes to master @BIueLightning

**Comment by BIueLightning** [comment]
Looks great!
The hologram is a really cool addition.

I just pushed some refactors to a new branch, which should make the code more readable in my opinion.
But that's personal taste of course.
Tell me if you like it :)

Also I think we can close this issue now, as the feature is added^^

**Comment by MagnusThor** [comment]
Thanks,  good work,  cleanng things up is a needed.    i do think the API is much more convinenr now after refactorring.

Feel free to refactor or add what ever you want :)

I do thik the procedual example is quite useful,  the hologramis more of a show case , i actually dont see anyone usng that.

**Comment by BIueLightning** [comment]
I'm happy you like it. 
Yeah, I might might make use of the procedual example aswell in my application.

One question:
In the setupRenderer method, if no backgroundUrl is provided, the promise just wouldn't resolve or reject in the previous implementation.
What should actually happen here?
```ts
private setupRenderer(backgroundUrl?: string): Promise<boolean | Error> {
        return new Promise<boolean | Error>(async (resolve, reject) => {
            try {
                if(!backgroundUrl)   // What should happen in this instance? 
           (...)
```

**Comment by MagnusThor** [comment]
@BIueLightning  i modified the `setupRenderer` method,   but i think we actually can skip that method, and to it inside the initialize method, feel free to refactor that if you have time.
